/*
 * File: app/model/ModelAlert.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.model.ModelAlert', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'timestamp',
        fields: [
            {
                name: 'timestamp',
                type: 'int'
            },
            {
                name: 'what'
            },
            {
                name: 'reason'
            },
            {
                name: 'level'
            },
            {
                name: 'kpiName'
            },
            {
                name: 'longitude'
            },
            {
                name: 'latitude'
            },
            {
                name: 'fingerprint'
            },
            {
                name: 'markerType'
            },
            {
                name: 'radius'
            },
            {
                name: 'color'
            },
            {
                name: 'kpiCaption'
            },
            {
                name: 'levelCaption'
            },
            {
                convert: function(v, rec) {
                    return new Date(v);
                },
                mapping: 'timestamp',
                name: 'dateTime',
                type: 'date'
            },
            {
                convert: function(v, rec) {
                    return Ext.Date.format(new Date(v), App.s.dateTimeFormat);
                },
                mapping: 'timestamp',
                name: 'dateTimeS'
            }
        ]
    }
});