/*
 * File: app/model/ModelChart.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.model.ModelChart', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'x',
                type: 'int'
            },
            {
                name: 'y1'
            },
            {
                name: 'y2'
            },
            {
                name: 'y3'
            },
            {
                name: 'y1Label'
            },
            {
                name: 'y2Label'
            },
            {
                name: 'y3Label'
            },
            {
                convert: function(v, rec) {
                    return new Date(rec.get("x"));
                },
                name: 'dateTime',
                type: 'date'
            },
            {
                convert: function(v, rec) {
                    return Ext.Date.format(new Date(rec.get("x")), App.s.timeFormat);
                },
                name: 'timeS',
                type: 'string'
            }
        ]
    }
});