/*
 * File: app/view/MyLineChart1.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.MyLineChart1', {
    extend: 'Ext.chart.CartesianChart',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom'
    ],

    config: {
        colors: [
            '#115fa6',
            '#94ae0a',
            '#a61120',
            '#ff8809',
            '#ffd13e',
            '#a61187',
            '#24ad9a',
            '#7c7474',
            '#a66111'
        ],
        axes: [
            {
                type: 'category',
                fields: [
                    'x'
                ]
            },
            {
                type: 'numeric',
                fields: [
                    'y1',
                    'y2'
                ],
                grid: {
                    odd: {
                        fill: '#e8e8e8'
                    }
                },
                position: 'left'
            }
        ],
        series: [
            {
                type: 'line',
                colors: 'rgba(0,200,0,0.3)',
                style: {
                    smooth: true,
                    stroke: 'rgb(0,200,0)',
                    
                },
                xField: 'x',
                yField: 'y1'
            },
            {
                type: 'line',
                colors: 'transparent',
                style: {
                    stroke: 'rgb(0,0,200)',
                    lineWidth: 2
                },
                xField: 'x',
                yField: 'y2'
            }
        ],
        interactions: [
            {
                type: 'panzoom'
            }
        ]
    }

});