/*
 * File: app/view/VAlertDetails.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VAlertDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.VAlertDetails',

    requires: [
        'Ext.Map',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        itemId: 'VAlertDetails',
        layout: 'fit',
        items: [
            {
                xtype: 'map',
                itemId: 'mymap',
                mapOptions: {
                    center: new google.maps.LatLng(46.151241,
                    14.995463),
                    zoom: 7
                }
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 46,
                margin: 0,
                padding: 0,
                items: [
                    {
                        xtype: 'button',
                        height: 46,
                        itemId: 'btnAlertDetailsBack',
                        margin: 0,
                        padding: '0 10',
                        ui: 'plain',
                        text: 'Back'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMymapMaprender',
                event: 'maprender',
                delegate: '#mymap'
            }
        ]
    },

    onMymapMaprender: function(map, gmap, eOpts) {
        map.setMapCenter({ latitude: 46.151241, longitude: 14.995463 });

        /*
        setTimeout(function() {
            map.panTo(map._pos);
        }, 1000);
        */

        var marker = new google.maps.Marker({
            position: map._pos,
            title: map._markerTitle,
            map: gmap
        });
    }

});