/*
 * File: app/view/VAlerts.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VAlerts', {
    extend: 'Ext.dataview.List',
    alias: 'widget.VAlerts',

    requires: [
        'Ext.XTemplate',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.plugin.PullRefresh'
    ],

    config: {
        itemId: 'VAlerts',
        scrollToTopOnRefresh: false,
        store: 'StoreAlerts',
        infinite: true,
        variableHeights: true,
        itemTpl: [
            '<div class="smaller-text">',
            '    <div class="title level-{levelCaption}">{reason}</div>',
            '    <div>{dateTimeS}</div>',
            '</div>',
            '<div class="disclosure-image"></div>'
        ],
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                height: 46,
                margin: 0,
                padding: 0,
                items: [
                    {
                        xtype: 'button',
                        height: 46,
                        itemId: 'btnAlertsBack',
                        margin: 0,
                        padding: '0 10',
                        ui: 'plain',
                        text: 'Back'
                    }
                ]
            }
        ],
        plugins: [
            {
                type: 'pullrefresh'
            }
        ]
    }

});