/*
 * File: app/view/VKPIs.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VKPIs', {
    extend: 'Ext.dataview.List',
    alias: 'widget.VKPIs',

    requires: [
        'Ext.XTemplate',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.plugin.PullRefresh'
    ],

    config: {
        itemId: 'VKPIs',
        emptyText: 'No KPIs',
        store: 'StoreKPIs',
        onItemDisclosure: false,
        itemTpl: [
            '<div class="icon {monitorName}"></div>',
            '<div class="with-icon">{kpiCaption}</div>',
            '<div class="disclosure-image"></div>'
        ],
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                height: 46,
                margin: 0,
                padding: 0,
                items: [
                    {
                        xtype: 'button',
                        height: 46,
                        itemId: 'btnKpisBack',
                        margin: 0,
                        padding: '0 10',
                        ui: 'plain',
                        text: 'Back'
                    }
                ]
            }
        ],
        plugins: [
            {
                type: 'pullrefresh'
            }
        ]
    }

});