/*
 * File: app/view/VLogin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VLogin', {
    extend: 'Ext.form.Panel',
    alias: 'widget.VLogin',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        centered: false,
        itemId: 'VLogin',
        scrollable: null,
        items: [
            {
                xtype: 'container',
                cls: 'centered',
                maxWidth: 500,
                items: [
                    {
                        xtype: 'container',
                        centered: false,
                        cls: 'centered',
                        html: '<img src="occapi_logo_login.png" />',
                        padding: '100 0 0 0',
                        width: 100
                    },
                    {
                        xtype: 'fieldset',
                        margin: '-10 10 10 10',
                        defaults: {
                            labelWidth: 60
                        },
                        title: '',
                        items: [
                            {
                                xtype: 'emailfield',
                                itemId: 'tfUser',
                                clearIcon: false,
                                label: '',
                                placeHolder: 'email@example.com'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'tfPass',
                                clearIcon: false,
                                label: '',
                                placeHolder: 'password'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                centered: false,
                                height: 40,
                                itemId: 'btnLogin',
                                margin: 10,
                                ui: 'action',
                                width: 150,
                                text: 'Sign in'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});