/*
 * File: app/view/VMain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VMain', {
    extend: 'Ext.Container',
    alias: 'widget.VMain',

    requires: [
        'OccapiMobile.view.VKPIGroups',
        'OccapiMobile.view.VAbout',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Sheet',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'VMain',
        layout: 'card',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                height: 46,
                margin: 0,
                padding: 0,
                title: 'KPI Groups',
                items: [
                    {
                        xtype: 'button',
                        cls: 'menu-btn',
                        height: 46,
                        itemId: 'btnMenu',
                        margin: 0,
                        padding: '0 10',
                        ui: 'plain',
                        text: 'Menu<div class="a"></div><div class="b"></div><div class="c"></div>'
                    }
                ]
            },
            {
                xtype: 'sheet',
                cls: 'menu',
                height: '100%',
                hidden: true,
                itemId: 'menu',
                left: 0,
                maxWidth: '100%',
                width: 210,
                hideOnMaskTap: true,
                layout: 'fit',
                enter: 'left',
                exit: 'left',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'menuList',
                        margin: '-1 0 0 0',
                        scrollable: false,
                        disableSelection: true,
                        itemTpl: [
                            '<div class="menu-icon" style="color:{color};">{icon}</div>',
                            '<div class="menu-text">{caption}</div>'
                        ],
                        store: 'StoreMenu'
                    }
                ]
            },
            {
                xtype: 'VKPIGroups'
            },
            {
                xtype: 'VAbout'
            }
        ]
    }

});