/*
 * File: app/view/VNav.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.VNav',

    requires: [
        'OccapiMobile.view.VLogin',
        'Ext.form.Panel',
        'Ext.navigation.Bar'
    ],

    config: {
        itemId: 'VNav',
        hideAnimation: {
            type: 'slideOut',
            direction: 'left'
        },
        layout: {
            type: 'card',
            animation: 'slide'
        },
        items: [
            {
                xtype: 'VLogin',
                title: 'Occapi Mobile'
            }
        ],
        navigationBar: {
            docked: 'top',
            hidden: true,
            layout: {
                type: 'hbox',
                pack: 'end'
            }
        }
    }

});