/*
 * File: app/view/VSettings.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.view.VSettings', {
    extend: 'Ext.Panel',
    alias: 'widget.VSettings',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Checkbox',
        'Ext.field.Slider',
        'Ext.field.Url'
    ],

    config: {
        itemId: 'VSettings',
        scrollable: 'vertical',
        hideAnimation: {
            type: 'slideOut',
            direction: 'right'
        },
        showAnimation: {
            type: 'slide',
            direction: 'left'
        },
        defaults: {
            margin: '0 10 0 10',
            defaults: {
                labelWidth: '75%',
                labelWrap: true,
                clearIcon: false
            }
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 46,
                margin: 0,
                padding: 0,
                title: 'Settings',
                items: [
                    {
                        xtype: 'button',
                        height: 46,
                        itemId: 'btnSettingsSave',
                        margin: 0,
                        padding: '0 10',
                        ui: 'plain',
                        text: 'Save'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        height: 46,
                        itemId: 'btnDefaults',
                        margin: 0,
                        padding: '0 10',
                        ui: 'plain',
                        text: 'Defaults'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'User',
                items: [
                    {
                        xtype: 'checkboxfield',
                        label: 'Remember me',
                        name: 'rememberMe',
                        checked: true
                    },
                    {
                        xtype: 'checkboxfield',
                        label: 'Automatic login',
                        name: 'autoLogin'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Alerts',
                items: [
                    {
                        xtype: 'checkboxfield',
                        label: 'Auto refresh alerts',
                        name: 'alertsRefreshEnabled',
                        checked: true
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'component',
                                cls: 'slider-value',
                                html: '5s',
                                width: 60
                            },
                            {
                                xtype: 'sliderfield',
                                flex: 1,
                                itemId: 'mysliderfield5',
                                padding: 6,
                                name: 'alertsRefreshTimeout',
                                value: [
                                    5
                                ],
                                maxValue: 30
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Charts',
                items: [
                    {
                        xtype: 'checkboxfield',
                        label: 'Auto refresh charts',
                        name: 'chartRefreshEnabled',
                        checked: true
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'component',
                                cls: 'slider-value',
                                html: '10s',
                                width: 60
                            },
                            {
                                xtype: 'sliderfield',
                                flex: 1,
                                itemId: 'mysliderfield6',
                                padding: 6,
                                name: 'chartRefreshTimeout',
                                value: [
                                    10
                                ],
                                maxValue: 30
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'API',
                items: [
                    {
                        xtype: 'urlfield',
                        label: 'URL',
                        labelWidth: 50,
                        name: 'apiUrl',
                        value: 'http://212.235.191.163:8080/inteliui/resources/',
                        placeHolder: 'http://example.com'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 10
            }
        ]
    }

});