/*
 * File: app/controller/CAlertDetails.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.controller.CAlertDetails', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#btnAlertDetailsBack": {
                tap: 'onBtnAlertDetailsBackTap'
            }
        }
    },

    onBtnAlertDetailsBackTap: function(button, e, eOpts) {
        App.VNav.pop();
    }

});