/*
 * File: app/controller/CKPIs.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.controller.CKPIs', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "list#VKPIs": {
                itemtap: 'onVKPIsItemTap'
            },
            "button#btnKpisBack": {
                tap: 'onBtnKpisBackTap'
            }
        }
    },

    onVKPIsItemTap: function(dataview, index, target, record, e, eOpts) {
        App.mask("Loading KPI data...");
        App.recKPI = record;
        App.sel.kpiName = record.get("kpiName");
        App.sel.monitor = record.get("monitorName");

        if(App.sel.monitor == "alert_on_list") {
            App.CAlerts.start();
        }
        else if(App.sel.monitor == "line_chart") {
            App.storeCharts.removeAll();

            App.CCharts.start();
        }
        else {
            Ext.Msg.alert("Error", "Unsupported KPI monitor.");
        }
    },

    onBtnKpisBackTap: function(button, e, eOpts) {
        App.VNav.pop();
        App.sel.groupName = null;
    }

});