/*
 * File: app/controller/CKPIGroups.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.controller.CKPIGroups', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "list#VKPIGroups": {
                itemtap: 'onVKPIGroupsItemTap',
                initialize: 'onVKPIGroupsInitialize'
            }
        }
    },

    onVKPIGroupsItemTap: function(dataview, index, target, record, e, eOpts) {
        App.mask("Loading KPI...");
        App.recKPIGroup = record;
        App.sel.groupName = record.get("kpiGroupName");
        App.storeKPIs.removeAll();
        App.storeKPIs.load({
            params: {
                groupName: App.sel.groupName,
                token: App.user.token
            },
            callback: function(records, operation, success) {
                if(success) {
                    var view = App.VNav.push({
                        xtype: "VKPIs",
                        title: "KPIs"
                    });
                    view.down("titlebar").setTitle(record.get("kpiGroupCaption"));
                }
                App.unmask();
            }
        });
    },

    onVKPIGroupsInitialize: function(component, eOpts) {
        component.element.on("swipe", function(e,t) {
            if(e.direction == "right" && e.startX <= 30) {
                App.VMenu.show();
            }
            else if(e.direction == "left" && e.startX >= App.VMenu.getWidth()) {

            }
        }, this);
    }

});