/*
 * File: app/controller/CMain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.controller.CMain', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#btnMenu": {
                tap: 'onBtnMenuTap'
            },
            "list#menuList": {
                itemtap: 'onMenuListItemTap'
            }
        }
    },

    onBtnMenuTap: function(button, e, eOpts) {
        if(App.VMenu.isHidden()) {
            App.VMenu.show();
        }
        else {
            App.VMenu.hide();
        }
    },

    onMenuListItemTap: function(dataview, index, target, record, e, eOpts) {
        var itemId = record.get("itemId");

        if (itemId == "VLogin") {
            App.CLogin.logout();
        }
        else if (itemId == "VSettings") {
            App.VNav.hide();
            settings.view.show();
            settings.load();
        }
        else {
            App.VMain.setActiveItem(itemId);
            App.VMain.down("titlebar").setTitle(record.get("caption"));
            App.VMenu.hide();
        }
    }

});