/*
 * File: app/controller/CNav.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.controller.CNav', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "navigationview#VNav": {
                initialize: 'onVNavInitialize'
            }
        }
    },

    onVNavInitialize: function(component, eOpts) {
        App.VNav = component;
        App.VMenu = component.down("sheet");
        App.VLogin = component.down("#VLogin");

        settings.view = Ext.Viewport.add({xtype: "VSettings", hidden: true});

        Ext.Viewport.element.on("swipe", function(e,t) {
            if(e.direction == "left") {
                App.VMenu.hide();
            }
        }, this);

        if(settings.get(settings.names.rememberMe)) {
            var user = getCookie("user");

            App.VLogin.down("#tfUser").setValue(user);

            if(settings.get(settings.names.autoLogin)) {
                var pass = getCookie("pass");

                App.VLogin.down("#tfPass").setValue(pass);
                App.CLogin.login();
            }
        }
    }

});