/*
 * File: app/controller/CSettings.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.controller.CSettings', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#btnSettingsSave": {
                tap: 'onBtnSettingsSaveTap'
            },
            "sliderfield#mysliderfield5": {
                change: 'onMysliderfield5Change',
                drag: 'onMysliderfield5Drag'
            },
            "sliderfield#mysliderfield6": {
                change: 'onMysliderfield6Change',
                drag: 'onMysliderfield6Drag'
            },
            "button#btnDefaults": {
                tap: 'onBtnDefaultsTap'
            }
        }
    },

    onBtnSettingsSaveTap: function(button, e, eOpts) {
        settings.save();

        if(settings.get(settings.names.rememberMe)) {
            setCookie("user", App.user.user);
            if(settings.get(settings.names.autoLogin)) {
                setCookie("pass", App.user.pass);
            }
        }

        //App.VNav.show();
        App.VMenu.setHidden(true);
        settings.view.hide();
        App.VNav.show();
    },

    onMysliderfield5Change: function(me, sl, thumb, newValue, oldValue, eOpts) {
        App.CSettings.sliderfieldValueChange(me);
    },

    onMysliderfield5Drag: function(sliderfield, sl, thumb, e, eOpts) {
        App.CSettings.sliderfieldValueChange(sliderfield);
    },

    onMysliderfield6Change: function(me, sl, thumb, newValue, oldValue, eOpts) {
        App.CSettings.sliderfieldValueChange(me);
    },

    onMysliderfield6Drag: function(sliderfield, sl, thumb, e, eOpts) {
        App.CSettings.sliderfieldValueChange(sliderfield);
    },

    onBtnDefaultsTap: function(button, e, eOpts) {
        Ext.Msg.confirm("Restore default settings", "Are you sure? <br />This requires applicaton restart.", function(btn) {
            if(btn == "yes") {
                settings.defaults();
                setCookie("user", "");
                setCookie("pass", "");
                App.VMenu.setHidden(true);
                settings.view.hide();
                App.VNav.show();
                location.reload();
            }
        }, this);
    },

    sliderfieldValueChange: function(sliderfield) {
        sliderfield.up().down("component").setHtml(sliderfield.getValue()[0] + "s");
    }

});