/*
 * File: app/store/StoreKPIGroups.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.store.StoreKPIGroups', {
    extend: 'Ext.data.Store',

    requires: [
        'OccapiMobile.model.ModelKPIGroup',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'OccapiMobile.model.ModelKPIGroup',
        storeId: 'StoreKPIGroups',
        proxy: {
            type: 'rest',
            extraParams: {
                action: 'kpigroup'
            },
            url: 'kpigroup/user/{token}',
            useDefaultXhrHeader: false,
            reader: {
                type: 'json'
            }
        }
    }
});