/*
 * File: app/store/StoreCharts.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.store.StoreCharts', {
    extend: 'Ext.data.Store',

    requires: [
        'OccapiMobile.model.ModelChart',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.util.Sorter'
    ],

    config: {
        model: 'OccapiMobile.model.ModelChart',
        storeId: 'StoreCharts',
        proxy: {
            type: 'rest',
            extraParams: {
                action: 'chart'
            },
            url: 'chart/kpi/{kpi}/monitor/{monitor}/token/{token}',
            useDefaultXhrHeader: false,
            reader: {
                type: 'json'
            }
        },
        sorters: {
            property: 'x'
        }
    }
});