/*
 * File: app/store/StoreMenu.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OccapiMobile.store.StoreMenu', {
    extend: 'Ext.data.Store',

    requires: [
        'OccapiMobile.model.ModelMenu',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        data: [
            {
                caption: 'KPI Groups',
                itemId: 'VKPIGroups',
                icon: 'l',
                color: 'rgb(206, 113, 27)'
            },
            {
                caption: 'About',
                itemId: 'VAbout',
                icon: 'i',
                color: 'rgb(65, 163, 63)'
            },
            {
                caption: 'Settings',
                itemId: 'VSettings',
                icon: 'x',
                color: 'rgb(169, 169, 169)'
            },
            {
                caption: 'Logout',
                itemId: 'VLogin',
                icon: 'Q',
                color: 'rgb(218, 87, 42)'
            }
        ],
        model: 'OccapiMobile.model.ModelMenu',
        storeId: 'StoreMenu',
        proxy: {
            type: 'ajax',
            url: 'menu.js',
            reader: {
                type: 'json'
            }
        }
    }
});